title: "Evolucion Poblacional por Grupos de Edad en America Latina ("
description: "Dataset demografico longitudinal con estructura de edad de la poblacion para 11 paises de America Latina en 4 cortes temporales (2000, 2010, 2020, 202"
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/evolucion-poblacional-por-grupos-de-edad-en-america-latina-2000-2023-dataset-dem"
